=== ouroboros8/high-frontier-cards/schema/card.schema.json
{
  "$id": "http://localhost:8800/card.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "back": {
      "anyOf": [
        {
          "$ref": "http://localhost:8800/sides/black.schema.json"
        },
        {
          "$ref": "http://localhost:8800/sides/purple.schema.json"
        }
      ]
    },
    "cardId": {
      "type": "integer"
    },
    "deck": {
      "enum": [
        "Thrusters",
        "Robonauts",
        "Refineries",
        "Reactors",
        "Radiators",
        "Generators",
        "GW/TW Thrusters",
        "Freighters",
        "Bernals",
        "Colonists"
      ]
    },
    "front": {
      "anyOf": [
        {
          "$ref": "http://localhost:8800/sides/white.schema.json"
        },
        {
          "$ref": "http://localhost:8800/sides/black.schema.json"
        }
      ]
    },
    "promotionColony": {
      "enum": [
        "C",
        "S",
        "M",
        "V",
        "D",
        "H",
        "Submarine",
        "Astrobiology",
        "Atmospheric",
        "Push"
      ]
    },
    "spectralType": {
      "enum": [
        "C",
        "S",
        "M",
        "V",
        "D",
        "H",
        "Any"
      ]
    }
  },
  "required": [
    "cardId",
    "deck",
    "front",
    "back"
  ],
  "title": "Card",
  "type": "object"
}

=== ouroboros8/high-frontier-cards/json/radiators.json
[{"cardId": 0, "deck": "Radiators", "front": {"name": "Bubble Membrane", "lightSide": {"mass": 0, "radHard": 1, "therms": 1}, "heavySide": {"mass": 1, "radHard": 0, "therms": 2}}, "back": {"name": "Electrostatic Membrane", "lightSide": {"mass": 0, "radHard": 3, "therms": 1}, "heavySide": {"mass": 1, "radHard": 2, "therms": 3}}, "spectralType": "C"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Dielectric X-Ray Window", "lightSide": {"mass": 4, "radHard": 7, "therms": 2}, "heavySide": {"mass": 5, "radHard": 7, "therms": 3}}, "back": {"name": "Graphene Crystal X-Ray Mirror", "lightSide": {"mass": 0, "radHard": 7, "therms": 1}, "heavySide": {"mass": 1, "radHard": 7, "therms": 2}}, "spectralType": "D"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "ETHER Charged Dust", "lightSide": {"mass": 1, "radHard": 1, "therms": 1}, "heavySide": {"mass": 2, "radHard": 1, "therms": 2}}, "back": {"name": "Curie Point", "lightSide": {"mass": 0, "radHard": 5, "therms": 1}, "heavySide": {"mass": 1, "radHard": 3, "therms": 3}}, "spectralType": "M"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Li Heatsink Fountain", "lightSide": {"mass": 2, "radHard": 6, "therms": 1}, "heavySide": {"mass": 3, "radHard": 6, "therms": 5, "ability": "Switch to light side after 1st use."}}, "back": {"name": "Thermochemical Heatsink Fountain", "lightSide": {"mass": 1, "radHard": 6, "therms": 1}, "heavySide": {"mass": 2, "radHard": 6, "therms": 6, "ability": "Switch to light side after 1st use."}}, "spectralType": "S"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Magnetocaloric Refrigerator", "lightSide": {"mass": 2, "radHard": 6, "therms": 3, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}], "ability": "This card can cool its own supports."}, "heavySide": {"mass": 3, "radHard": 6, "therms": 4, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}], "ability": "This card can cool its own supports."}}, "back": {"name": "Nuclear Fuel Spin Polarizer", "lightSide": {"mass": 0, "radHard": 5, "therms": 1}, "heavySide": {"mass": 1, "radHard": 4, "therms": 2}}, "spectralType": "S"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Microtube Array", "lightSide": {"mass": 2, "radHard": 1, "therms": 2}, "heavySide": {"mass": 3, "radHard": 0, "therms": 3}}, "back": {"name": "Marangoni Flow", "lightSide": {"mass": 0, "radHard": 2, "therms": 2}, "heavySide": {"mass": 1, "radHard": 1, "therms": 3}}, "spectralType": "C"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Mo / Li Heat Pipe", "lightSide": {"mass": 1, "radHard": 2, "therms": 2}, "heavySide": {"mass": 2, "radHard": 1, "therms": 3}}, "back": {"name": "Tin Droplet", "lightSide": {"mass": 0, "radHard": 3, "therms": 2}, "heavySide": {"mass": 1, "radHard": 2, "therms": 3}}, "spectralType": "M"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Qu Tube", "lightSide": {"mass": 1, "radHard": 4, "therms": 1}, "heavySide": {"mass": 4, "radHard": 2, "therms": 2}}, "back": {"name": "ANDR / In Dream Pipe", "lightSide": {"mass": 0, "radHard": 3, "therms": 2}, "heavySide": {"mass": 1, "radHard": 2, "therms": 3}}, "spectralType": "M"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "SS / NaK Pumped Loop", "lightSide": {"mass": 2, "radHard": 1, "therms": 2}, "heavySide": {"mass": 4, "radHard": 0, "therms": 3}}, "back": {"name": "Hula-Hoop", "lightSide": {"mass": 1, "radHard": 6, "therms": 2}, "heavySide": {"mass": 2, "radHard": 6, "therms": 3}}, "spectralType": "M"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Salt-Cooled Reflux Tube", "lightSide": {"mass": 3, "radHard": 4, "therms": 2}, "heavySide": {"mass": 4, "radHard": 4, "therms": 3}}, "back": {"name": "Buckytube Filament", "lightSide": {"mass": 0, "radHard": 4, "therms": 2}, "heavySide": {"mass": 1, "radHard": 3, "therms": 3}}, "spectralType": "C"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Steel / Pb-Bi Pumped Loop", "lightSide": {"mass": 2, "radHard": 3, "therms": 1}, "heavySide": {"mass": 4, "radHard": 2, "therms": 2}}, "back": {"name": "Pulsating Heat Pipe", "lightSide": {"mass": 1, "radHard": 1, "therms": 2}, "heavySide": {"mass": 2, "radHard": 1, "therms": 4}}, "spectralType": "M"}, {"cardId": 0, "deck": "Radiators", "front": {"name": "Ti / K Heat Pipe", "lightSide": {"mass": 2, "radHard": 3, "therms": 1}, "heavySide": {"mass": 4, "radHard": 2, "therms": 2}}, "back": {"name": "Flux-Pinned Superthermal", "lightSide": {"mass": 1, "radHard": 5, "therms": 1}, "heavySide": {"mass": 2, "radHard": 5, "therms": 3}}, "spectralType": "M"}]

=== ouroboros8/high-frontier-cards/json/gw-tw-thrusters.json
[
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Amat-Catalyzed Fission-Fusion",
      "mass": 3,
      "radHard": 9,
      "thrustTriangle": {
        "thrust": 10,
        "fuelConsumption": "1/3",
        "afterburn": 2,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "reactor",
          "subtypes": [
            "X"
          ]
        },
        {
          "type": "cooling",
          "therms": 2
        }
      ]
    },
    "back": {
      "name": "Amat-Initiated H-B Magnetic-Inertial",
      "mass": 1,
      "radHard": 10,
      "future": "MINI-BLACK HOLE FUTURE: Req = Industrialized centaur with 10 isotope FTs. Effects = double all isotope refuel, 10 VP.",
      "thrustTriangle": {
        "thrust": 8,
        "fuelConsumption": "0",
        "afterburn": 5,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 1
        }
      ]
    },
    "spectralType": "S",
    "promotionColony": "D"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Dense Plasma H-B Focus Fusion",
      "mass": 1,
      "radHard": 8,
      "thrustTriangle": {
        "thrust": 2,
        "fuelConsumption": "1/10",
        "afterburn": 5,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        }
      ]
    },
    "back": {
      "name": "Crossfire H-B Focus Fusion",
      "mass": 1,
      "radHard": 9,
      "future": "PROTIUM FUSION FUTURE: Req = Promoted Bernal with H Dirtside. Effects = double all isotope refuel, 10 VP.",
      "thrustTriangle": {
        "thrust": 3,
        "fuelConsumption": "0",
        "afterburn": 9,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        }
      ]
    },
    "spectralType": "D",
    "promotionColony": "D"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Levitated Dipole 6Li-H Fusion",
      "mass": 4,
      "radHard": 5,
      "thrustTriangle": {
        "thrust": 2,
        "fuelConsumption": "0",
        "afterburn": 4,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "cooling",
          "therms": 1
        }
      ]
    },
    "back": {
      "name": "Dusty Plasma",
      "mass": 2,
      "radHard": 8,
      "future": "MASS BEAM FUTURE: Req = Promoted Bernal with Io or Triton Dirtside. Effects = your Powersat adds +2 thrust, 7 VP.",
      "thrustTriangle": {
        "thrust": 2,
        "fuelConsumption": "0",
        "afterburn": 9,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "cooling",
          "therms": 3
        }
      ]
    },
    "spectralType": "V",
    "promotionColony": "S"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Mini-Mag Orion Z-Pinch Fission",
      "mass": 1,
      "radHard": 9,
      "thrustTriangle": {
        "thrust": 12,
        "fuelConsumption": "1/3",
        "afterburn": 0,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 2
        }
      ]
    },
    "back": {
      "name": "Solem Medusa Tugged Orion",
      "mass": 6,
      "radHard": 9,
      "future": "LITHIATED AMMONIA ICE STARSHIP FUTURE: Req = Ad astra exit with 10 isotope fuel. Effect = 14 VP.",
      "thrustTriangle": {
        "thrust": 9,
        "fuelConsumption": "0",
        "afterburn": 3,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        }
      ]
    },
    "spectralType": "M",
    "promotionColony": "D"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Salt-Water Zubrin",
      "mass": 1,
      "radHard": 6,
      "thrustTriangle": {
        "thrust": 14,
        "fuelConsumption": "1/2",
        "afterburn": 1,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "cooling",
          "therms": 5
        }
      ]
    },
    "back": {
      "name": "Zubrin-GDM",
      "mass": 3,
      "radHard": 8,
      "future": "SPACEFARING FUTURE: Req = Bernal with 8+ dirtside hydration. Effects = Allowed 1 extra Colonist, 7 VP.",
      "thrustTriangle": {
        "thrust": 6,
        "fuelConsumption": "0",
        "afterburn": 8,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 4
        }
      ]
    },
    "spectralType": "S",
    "promotionColony": "M"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "Spheromak 3He-D Magnetic Fusion",
      "mass": 4,
      "radHard": 8,
      "thrustTriangle": {
        "thrust": 6,
        "fuelConsumption": "1/10",
        "afterburn": 6,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "e"
          ]
        },
        {
          "type": "cooling",
          "therms": 4
        }
      ]
    },
    "back": {
      "name": "Colliding FRC 3He-D Fusion",
      "mass": 3,
      "radHard": 9,
      "future": "ENZMANN STARSHIP FUTURE: Req = Ad astra exit with 2 Promoted Colonists + Mobile Factory. Effect = 12 VP.",
      "thrustTriangle": {
        "thrust": 4,
        "fuelConsumption": "0",
        "afterburn": 10,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 2
        }
      ]
    },
    "spectralType": "H",
    "promotionColony": "H"
  },
  {
    "cardId": 0,
    "deck": "GW/TW Thrusters",
    "front": {
      "name": "VISTA D-T Inertial Fusion",
      "mass": 5,
      "radHard": 8,
      "thrustTriangle": {
        "thrust": 9,
        "fuelConsumption": "1/4",
        "afterburn": 3,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 2
        }
      ]
    },
    "back": {
      "name": "Daedalus 3He-D Inertial Fusion",
      "mass": 5,
      "radHard": 9,
      "future": "FUSION CANDLE FUTURE: Req = Triton Colony & Promoted Bernal with Neptune Aerostat Dirtside. Effects = double all isotope refuel, 14 VP.",
      "thrustTriangle": {
        "thrust": 11,
        "fuelConsumption": "0",
        "afterburn": 8,
        "fuelType": "isotope"
      },
      "supportRequirements": [
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        },
        {
          "type": "cooling",
          "therms": 3
        }
      ]
    },
    "spectralType": "H",
    "promotionColony": "H"
  }
]

=== ouroboros8/high-frontier-cards/json/refineries.json
[{"cardId": 0, "deck": "Refineries", "front": {"name": "Atomic Layer Deposition", "mass": 2, "radHard": 2, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Ilmenite Semiconductor Film", "mass": 2, "radHard": 6, "airEater": false, "ability": "POWER GIRDLE: If used to industrialize a non-atmospheric site of size 8+, you permanently gain the Powersat faction privilege."}, "spectralType": "V"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Basalt Fiber Spinning", "mass": 3, "radHard": 5, "airEater": false, "supportRequirements": [{"type": "reactor", "subtypes": ["\u223f", "\ud83d\udca3", "X"]}]}, "back": {"name": "Von Neumann Santa Claus Machine", "mass": 2, "radHard": 5, "airEater": false, "ability": "DIVINING NUBOTS: -1 ISRU for Colocated ISRU platform."}, "spectralType": "S"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "CVD Molding", "mass": 3, "radHard": 5, "airEater": false}, "back": {"name": "Carbonyl Volatilization", "mass": 2, "radHard": 5, "airEater": false, "ability": "THORIUM BREEDER: -3 to Colocated size rolls on S Sites."}, "spectralType": "M"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Carbo-Chlorination", "mass": 2, "radHard": 4, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Solar Carbotherm", "mass": 2, "radHard": 5, "airEater": false, "ability": "ARCOLOGY: Decommissioning of a robonaut is not needed when this is used to industrialize in the zones Mercury, Venus, Earth"}, "spectralType": "V"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Electroforming", "mass": 3, "radHard": 3, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Impact Mold Sinter", "mass": 3, "radHard": 5, "airEater": false, "ability": "FOAMED NICKEL: -1 to Colocated size rolls."}, "spectralType": "M"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Fluidized Bed", "mass": 3, "radHard": 4, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Atmospheric Scoop", "mass": 1, "radHard": 5, "airEater": true, "ability": "SCOOP: If operational, this card makes adjacent or colocated aerostat sites into [2 hydration]", "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "spectralType": "V"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Foamglass Sintering", "mass": 3, "radHard": 4, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Laser-Heated Pedestal Growth", "mass": 1, "radHard": 5, "airEater": false, "ability": "SUPERLENS: -1 to all Colocated raygun size rolls.", "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "spectralType": "D"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Froth Flotation", "mass": 3, "radHard": 5, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Femtochemistry", "mass": 2, "radHard": 8, "airEater": false, "ability": "SCAVENGING: If Colocated, doubles FTs during site refuel."}, "spectralType": "D"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "ISRU Sabatier", "mass": 3, "radHard": 4, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Biophytolytic Algal Farm", "mass": 3, "radHard": 5, "airEater": false, "ability": "COMET LICHEN: -2 to Colocated size rolls on D Sites."}, "spectralType": "V"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "In-Situ Leaching", "mass": 3, "radHard": 3, "airEater": false, "supportRequirements": [{"type": "reactor", "subtypes": ["\u223f", "\ud83d\udca3", "X"]}]}, "back": {"name": "Termite Nest", "mass": 1, "radHard": 3, "airEater": false, "ability": "MINE REVIVAL: As an op, remove a busted disk and place Claim on a Colocated Site of Size 2+.", "supportRequirements": [{"type": "reactor", "subtypes": ["\u223f", "\ud83d\udca3", "X"]}]}, "spectralType": "D"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Magma Electrolysis", "mass": 3, "radHard": 3, "airEater": false, "supportRequirements": [{"type": "generator", "subtypes": ["e"]}]}, "back": {"name": "Ionosphere Lasing", "mass": 2, "radHard": 6, "airEater": false, "ability": "IONOSAT: If used to industrialize an Atmospheric Site, permanently gain the Powersat faction privilege."}, "spectralType": "V"}, {"cardId": 0, "deck": "Refineries", "front": {"name": "Supercritical Drying", "mass": 1, "radHard": 5, "airEater": false, "supportRequirements": [{"type": "reactor", "subtypes": ["X"]}]}, "back": {"name": "Solid Flame", "mass": 0, "radHard": 5, "airEater": false, "ability": "JELLYBOTS: Colocated industrialization is a free action.", "supportRequirements": [{"type": "reactor", "subtypes": ["X"]}]}, "spectralType": "H"}]

=== ouroboros8/high-frontier-cards/json/freighters.json
[
  {
    "cardId": 165,
    "deck": "Freighters",
    "front": {
      "name": "Fission-Heated Steam",
      "mass": 0,
      "radHard": 5,
      "loadLimit": 2,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "∿"
          ]
        }
      ]
    },
    "back": {
      "name": "Fission GCR",
      "mass": 1,
      "radHard": 6,
      "loadLimit": 6,
      "factoryLoadingOnly": false,
      "bonusPivots": 0,
      "ability": "Can liftoff/land on Sites that are less than size 6 without factory-assist.",
      "future": "EXOPLANET HUNT FUTURE: Req = Claim Sedna. Effect = (Endgame) 12 VP.",
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "∿"
          ]
        }
      ]
    },
    "spectralType": "Any",
    "promotionColony": "M"
  },
  {
    "cardId": 168,
    "deck": "Freighters",
    "front": {
      "name": "Fusion Fragment Sail",
      "mass": 2,
      "radHard": 1,
      "loadLimit": 2,
      "factoryLoadingOnly": false,
      "bonusPivots": 1,
      "ability": "Immune to flares & radiation belts."
    },
    "back": {
      "name": "Antiproton Sail and Harvester",
      "mass": 2,
      "radHard": 9,
      "loadLimit": 6,
      "factoryLoadingOnly": false,
      "bonusPivots": 4,
      "ability": "+1 net thrust if starting its move on a radiation belt.",
      "future": "ANTIMATTER FUTURE: Req = Promoted Bernal with S Dirtside. Effects = double isotope refuel, 10 VP."
    },
    "spectralType": "V",
    "promotionColony": "M"
  },
  {
    "cardId": 169,
    "deck": "Freighters",
    "front": {
      "name": "HIIPER Beam Rider",
      "mass": 4,
      "radHard": 4,
      "loadLimit": 4,
      "factoryLoadingOnly": false,
      "bonusPivots": 1,
      "supports": [
        {
          "type": "generator",
          "subtypes": [
            "e"
          ]
        }
      ]
    },
    "back": {
      "name": "Magnetic Mirror Beam Rider",
      "mass": 3,
      "radHard": 6,
      "loadLimit": 5,
      "factoryLoadingOnly": false,
      "bonusPivots": 3,
      "ability": "Can liftoff/land on Sites that are less than size 6 without factory-assist.",
      "future": "STAR WISP FUTURE: Req = Promoted Freighter (End game) at either neutrino sunlens (6 VP) or EM sunlens = 11 VP.",
      "supports": [
        {
          "type": "generator",
          "subtypes": [
            "e"
          ]
        }
      ]
    },
    "spectralType": "V",
    "promotionColony": "Push"
  },
  {
    "cardId": 163,
    "deck": "Freighters",
    "front": {
      "name": "Inflatable Solar-Heated",
      "mass": 0,
      "radHard": 5,
      "loadLimit": 2,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "ability": "SOLAR HEATED: If not using Powersat, may move out only as far as the Ceres zone."
    },
    "back": {
      "name": "Archimedes Palmer Lens",
      "mass": 0,
      "radHard": 10,
      "loadLimit": 5,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "ability": "SOLAR HEATED: If not using Powersat, may move out only as far as the Jupiter zone.",
      "future": "TERRAFORM FUTURE: Req = Promoted Bernal at a non-Martian Atmospheric Dirtside. Effect = 8 VP."
    },
    "spectralType": "Any",
    "promotionColony": "C"
  },
  {
    "cardId": 166,
    "deck": "Freighters",
    "front": {
      "name": "Poodle Steam",
      "mass": 0,
      "radHard": 7,
      "loadLimit": 2,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "ability": "RADIOISOTOPE: +2 thrust if its move starts on a Factory."
    },
    "back": {
      "name": "D-Nanotube Dirt Launcher",
      "mass": 0,
      "radHard": 9,
      "loadLimit": 3,
      "factoryLoadingOnly": false,
      "bonusPivots": 0,
      "future": "BEANSTALK FUTURE: Req = 3+ Space Elevators built by any player. Effect (Endgame) = +3 VP for each Factory connected to a Space Elevator."
    },
    "spectralType": "Any",
    "promotionColony": "S"
  },
  {
    "cardId": 164,
    "deck": "Freighters",
    "front": {
      "name": "Rotary Dirt Launcher",
      "mass": 5,
      "radHard": 4,
      "loadLimit": 2,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "∿"
          ]
        },
        {
          "type": "generator",
          "subtypes": [
            "e"
          ]
        }
      ]
    },
    "back": {
      "name": "KESTS Hoop Dirt Launcher",
      "mass": 15,
      "radHard": 8,
      "loadLimit": 15,
      "factoryLoadingOnly": true,
      "bonusPivots": 0,
      "future": "BEEHIVE ARK FUTURE: Req = Promoted Bernal anchored at a Synodic Comet. Effect = 7 VP.",
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "∿"
          ]
        },
        {
          "type": "generator",
          "subtypes": [
            "e"
          ]
        }
      ]
    },
    "spectralType": "Any",
    "promotionColony": "C"
  },
  {
    "cardId": 167,
    "deck": "Freighters",
    "front": {
      "name": "Z-Pinch D-T / 6Li Fusion",
      "mass": 5,
      "radHard": 3,
      "loadLimit": 3,
      "factoryLoadingOnly": false,
      "bonusPivots": 1,
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "X"
          ]
        },
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        }
      ]
    },
    "back": {
      "name": "Z-Pinch 3He-D Target Fusion",
      "mass": 2,
      "radHard": 6,
      "loadLimit": 6,
      "factoryLoadingOnly": false,
      "bonusPivots": 2,
      "future": "GOLDEN APPLES FUTURE: Req = Industrialize Kreutz Sungrazer. Effects = Ignore solar flares, 14 VP.",
      "supports": [
        {
          "type": "reactor",
          "subtypes": [
            "X"
          ]
        },
        {
          "type": "generator",
          "subtypes": [
            "⟛"
          ]
        }
      ]
    },
    "spectralType": "V",
    "promotionColony": "H"
  }
]
